# Generated by Django 3.1.6 on 2021-03-21 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactform',
            fields=[
                ('contactfrom_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=100)),
                ('mobile_number', models.IntegerField(default=9999999999)),
                ('email_id', models.EmailField(default='', max_length=254)),
                ('sub', models.CharField(max_length=500)),
            ],
        ),
    ]
